In [1]:
import numpy as np
import pandas as pd

In [2]:
df1=pd.read_csv(r'C:\Users\User\Downloads\Outlier Dataset\Feature Scaling\social.csv')

In [3]:
df1

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [4]:
df1.columns

Index(['User ID', 'Gender', 'Age', 'EstimatedSalary', 'Purchased'], dtype='object')

In [5]:
df1.drop(['User ID','Gender'],axis=1,inplace=True)

In [6]:
df1

Age  EstimatedSalary  Purchased
0     19            19000          0
1     35            20000          0
2     26            43000          0
3     27            57000          0
4     19            76000          0
..   ...              ...        ...
395   46            41000          1
396   51            23000          1
397   50            20000          1
398   36            33000          0
399   49            36000          1

[400 rows x 3 columns]

In [8]:
X=df1[['Age','EstimatedSalary']]

In [9]:
X

Age  EstimatedSalary
0     19            19000
1     35            20000
2     26            43000
3     27            57000
4     19            76000
..   ...              ...
395   46            41000
396   51            23000
397   50            20000
398   36            33000
399   49            36000

[400 rows x 2 columns]

In [10]:
y=df1['Purchased']

In [11]:
y

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
Xtrain,Xtest,ytrain,ytest=train_test_split(X,y,test_size=0.2)

In [14]:
Xtrain.shape

(320, 2)

In [15]:
Xtest.shape

(80, 2)

In [16]:
X.shape

(400, 2)

In [17]:
ytrain.shape

(320,)

In [18]:
ytest.shape

(80,)

In [19]:
y.shape

(400,)

## Standardization

In [20]:
from sklearn.preprocessing import StandardScaler

In [21]:
ss=StandardScaler()

In [22]:
ss

StandardScaler()

In [23]:
ss.fit(Xtrain)

StandardScaler()

In [24]:
Xtrain_ss=ss.transform(Xtrain)

In [25]:
Xtrain

Age  EstimatedSalary
240   42           149000
154   40            47000
96    35            25000
300   58            38000
192   29            43000
..   ...              ...
381   48            33000
187   33            41000
262   55           125000
291   49            89000
364   42           104000

[320 rows x 2 columns]

In [26]:
Xtrain_ss

array([[ 0.41410134,  2.43600656],
       [ 0.22452705, -0.64319932],
       [-0.24940868, -1.30734176],
       [ 1.93069567, -0.91489395],
       [-0.81813155, -0.76395249],
       [ 2.02548282, -1.18658859],
       [-0.9129187 , -1.09602371],
       [-1.76600301, -1.42809493],
       [ 0.41410134,  1.19828655],
       [-0.05983439,  0.20207289],
       [-0.9129187 , -0.94508224],
       [-0.24940868, -0.73376419],
       [ 0.03495276, -0.52244614],
       [ 0.98282422,  1.53035777],
       [ 1.64633424, -0.88470566],
       [ 0.12973991,  0.1416963 ],
       [-1.38685443,  0.41339094],
       [ 0.3193142 ,  0.11150801],
       [-1.29206728, -1.24696517],
       [-1.57642872, -0.00924516],
       [-0.81813155,  0.35301435],
       [ 0.69846278, -1.09602371],
       [ 0.88803707, -1.45828322],
       [-0.53377011,  0.95678021],
       [ 1.55154709,  1.19828655],
       [ 0.3193142 , -1.15640029],
       [-0.62855726, -1.03564712],
       [-1.00770584, -1.5488481 ],
       [ 1.07761136,

In [27]:
Xtest_ss=ss.transform(Xtest)

In [28]:
Xtest

Age  EstimatedSalary
107   27            89000
358   40            71000
85    31           118000
235   46            79000
252   48           134000
..   ...              ...
136   20            82000
375   46            32000
168   29           148000
47    27            54000
49    31            89000

[80 rows x 2 columns]

In [29]:
Xtest_ss

array([[-1.00770584,  0.62470899],
       [ 0.22452705,  0.08131971],
       [-0.62855726,  1.50016948],
       [ 0.79324993,  0.32282606],
       [ 0.98282422,  1.98318217],
       [-0.81813155,  0.44357923],
       [-0.05983439, -1.06583542],
       [-0.81813155,  0.44357923],
       [-0.05983439,  0.74546216],
       [-0.05983439,  0.35301435],
       [-0.72334441, -1.5488481 ],
       [ 0.3193142 , -0.25075151],
       [ 0.79324993, -1.21677688],
       [-1.48164157, -0.40169297],
       [-0.15462153,  1.74167582],
       [ 0.88803707,  2.2850651 ],
       [-0.24940868,  2.37562997],
       [ 1.55154709,  1.07753338],
       [ 0.41410134,  0.1416963 ],
       [-0.53377011,  1.46998119],
       [-0.72334441,  2.01337046],
       [-0.34419582,  1.4096046 ],
       [ 0.69846278, -0.7035759 ],
       [-1.10249299,  1.50016948],
       [-0.15462153, -0.43188127],
       [ 0.03495276, -0.09981004],
       [-0.05983439, -0.40169297],
       [ 0.98282422, -1.06583542],
       [-0.24940868,

## Score on normal data

In [30]:
from sklearn.linear_model import LogisticRegression

In [37]:
logreg=LogisticRegression()

In [38]:
logreg

LogisticRegression()

In [39]:
logreg.fit(Xtrain,ytrain)

LogisticRegression()

In [40]:
logreg.score(Xtest,ytest)

0.5625

## Score on standardized data(scaled data)

In [41]:
from sklearn.linear_model import LogisticRegression

In [42]:
logstd=LogisticRegression()

In [43]:
logstd

LogisticRegression()

In [44]:
logstd.fit(Xtrain_ss,ytrain)

LogisticRegression()

In [45]:
logstd.score(Xtest_ss,ytest)

0.8

## Normalization

In [46]:
from sklearn.preprocessing import MinMaxScaler

In [47]:
minmax=MinMaxScaler()

In [48]:
minmax.fit(Xtrain)

MinMaxScaler()

In [49]:
Xtrain_minmax=minmax.transform(Xtrain)

In [50]:
Xtest_minmax=minmax.transform(Xtest)

In [51]:
Xtrain

Age  EstimatedSalary
240   42           149000
154   40            47000
96    35            25000
300   58            38000
192   29            43000
..   ...              ...
381   48            33000
187   33            41000
262   55           125000
291   49            89000
364   42           104000

[320 rows x 2 columns]

In [52]:
Xtrain_minmax

array([[0.57142857, 0.99259259],
       [0.52380952, 0.23703704],
       [0.4047619 , 0.07407407],
       [0.95238095, 0.17037037],
       [0.26190476, 0.20740741],
       [0.97619048, 0.1037037 ],
       [0.23809524, 0.12592593],
       [0.02380952, 0.04444444],
       [0.57142857, 0.68888889],
       [0.45238095, 0.44444444],
       [0.23809524, 0.16296296],
       [0.4047619 , 0.21481481],
       [0.47619048, 0.26666667],
       [0.71428571, 0.77037037],
       [0.88095238, 0.17777778],
       [0.5       , 0.42962963],
       [0.11904762, 0.4962963 ],
       [0.54761905, 0.42222222],
       [0.14285714, 0.08888889],
       [0.07142857, 0.39259259],
       [0.26190476, 0.48148148],
       [0.64285714, 0.12592593],
       [0.69047619, 0.03703704],
       [0.33333333, 0.62962963],
       [0.85714286, 0.68888889],
       [0.54761905, 0.11111111],
       [0.30952381, 0.14074074],
       [0.21428571, 0.01481481],
       [0.73809524, 0.37037037],
       [0.11904762, 0.0962963 ],
       [0.

In [53]:
Xtest

Age  EstimatedSalary
107   27            89000
358   40            71000
85    31           118000
235   46            79000
252   48           134000
..   ...              ...
136   20            82000
375   46            32000
168   29           148000
47    27            54000
49    31            89000

[80 rows x 2 columns]

In [54]:
Xtest_minmax

array([[0.21428571, 0.54814815],
       [0.52380952, 0.41481481],
       [0.30952381, 0.76296296],
       [0.66666667, 0.47407407],
       [0.71428571, 0.88148148],
       [0.26190476, 0.5037037 ],
       [0.45238095, 0.13333333],
       [0.26190476, 0.5037037 ],
       [0.45238095, 0.57777778],
       [0.45238095, 0.48148148],
       [0.28571429, 0.01481481],
       [0.54761905, 0.33333333],
       [0.66666667, 0.0962963 ],
       [0.0952381 , 0.2962963 ],
       [0.42857143, 0.82222222],
       [0.69047619, 0.95555556],
       [0.4047619 , 0.97777778],
       [0.85714286, 0.65925926],
       [0.57142857, 0.42962963],
       [0.33333333, 0.75555556],
       [0.28571429, 0.88888889],
       [0.38095238, 0.74074074],
       [0.64285714, 0.22222222],
       [0.19047619, 0.76296296],
       [0.42857143, 0.28888889],
       [0.47619048, 0.37037037],
       [0.45238095, 0.2962963 ],
       [0.71428571, 0.13333333],
       [0.4047619 , 0.28148148],
       [0.19047619, 0.48148148],
       [0.

## Score on Normalized data(scaled data)

In [55]:
from sklearn.linear_model import LogisticRegression

In [56]:
lognorm=LogisticRegression()

In [57]:
lognorm

LogisticRegression()

In [58]:
lognorm.fit(Xtrain_minmax,ytrain)

LogisticRegression()

In [59]:
lognorm.score(Xtest_minmax,ytest)

0.75