In [1]:
import numpy as np
import pandas as pd

In [2]:
df1=pd.read_csv(r'C:\Users\User\Downloads\ML Dataset\Linear Regression\houseprice.csv')

In [3]:
df1

area   price
0  2000  500000
1  2600  530000
2  2800  550000
3  3000  565000
4  3200  610000
5  3400  650000
6  3600  680000
7  3800  700000
8  4000  725000

In [4]:
df1.columns

Index(['area', 'price'], dtype='object')

In [5]:
df1['area']

0    2000
1    2600
2    2800
3    3000
4    3200
5    3400
6    3600
7    3800
8    4000
Name: area, dtype: int64

In [6]:
X=df1[['area']]

In [7]:
X

area
0  2000
1  2600
2  2800
3  3000
4  3200
5  3400
6  3600
7  3800
8  4000

In [8]:
y=df1['price']

In [9]:
y

0    500000
1    530000
2    550000
3    565000
4    610000
5    650000
6    680000
7    700000
8    725000
Name: price, dtype: int64

In [10]:
type(X)

pandas.core.frame.DataFrame

In [11]:
type(y)

pandas.core.series.Series

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
Xtrain,Xtest,ytrain,ytest=train_test_split(X,y,test_size=0.2)

In [14]:
X.shape,Xtrain.shape,Xtest.shape

((9, 1), (7, 1), (2, 1))

In [15]:
y.shape,ytrain.shape,ytest.shape

((9,), (7,), (2,))

## Model Building

In [16]:
from sklearn.linear_model import LinearRegression

In [17]:
lreg=LinearRegression() # Model Building done

In [18]:
lreg

LinearRegression()

In [19]:
lreg.fit(Xtrain,ytrain)

LinearRegression()

In [20]:
lreg.coef_ # Value of slope(m)

array([121.07142857])

In [21]:
lreg.intercept_ # Value of C

231142.85714285704

In [22]:
lreg.score(Xtest,ytest)

0.9575325963718823

In [23]:
df1

area   price
0  2000  500000
1  2600  530000
2  2800  550000
3  3000  565000
4  3200  610000
5  3400  650000
6  3600  680000
7  3800  700000
8  4000  725000

In [26]:
lreg.predict([[2300]]) # double square brackets here

array([509607.14285714])

In [32]:
lreg.predict([[2200]]) # Doubt here

array([497500.])

In [33]:
val=[2200,2900,3300,3700,4500]

In [34]:
for i in val:
    print(i,end='==')
    print(lreg.predict([[i]]))

2200==[497500.]
2900==[582250.]
3300==[630678.57142857]
3700==[679107.14285714]
4500==[775964.28571429]
