In [21]:
import nltk
import pandas as pd

In [2]:
from sklearn.feature_extraction.text import CountVectorizer

In [8]:
sent=[
    'Dog is best friend of human',
    'Brown Dog jumps over Green Gate to Chase Black Cat',
    'Black Cat is Playing in ground',
    'Cat is quick to react over dog'
]

In [9]:
sent

['Dog is best friend of human',
 'Brown Dog jumps over Green Gate to Chase Black Cat',
 'Black Cat is Playing in ground',
 'Cat is quick to react over dog']

In [10]:
cvec=CountVectorizer()

In [11]:
cvec.fit(sent)

CountVectorizer()

In [12]:
cvec.get_feature_names_out()

array(['best', 'black', 'brown', 'cat', 'chase', 'dog', 'friend', 'gate',
       'green', 'ground', 'human', 'in', 'is', 'jumps', 'of', 'over',
       'playing', 'quick', 'react', 'to'], dtype=object)

In [17]:
cvec.get_feature_names_out().size

20

In [13]:
cvec.vocabulary_

{'dog': 5,
 'is': 12,
 'best': 0,
 'friend': 6,
 'of': 14,
 'human': 10,
 'brown': 2,
 'jumps': 13,
 'over': 15,
 'green': 8,
 'gate': 7,
 'to': 19,
 'chase': 4,
 'black': 1,
 'cat': 3,
 'playing': 16,
 'in': 11,
 'ground': 9,
 'quick': 17,
 'react': 18}

In [14]:
sent

['Dog is best friend of human',
 'Brown Dog jumps over Green Gate to Chase Black Cat',
 'Black Cat is Playing in ground',
 'Cat is quick to react over dog']

In [18]:
cvec_sent=cvec.transform(sent)

In [19]:
cvec_sent

<4x20 sparse matrix of type '<class 'numpy.int64'>'
	with 29 stored elements in Compressed Sparse Row format>

In [20]:
cvec_sent.toarray()

array([[1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1],
       [0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1]],
      dtype=int64)

In [22]:
pd.DataFrame(cvec_sent.toarray())

0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  17  18  \
0   1   0   0   0   0   1   1   0   0   0   1   0   1   0   1   0   0   0   0   
1   0   1   1   1   1   1   0   1   1   0   0   0   0   1   0   1   0   0   0   
2   0   1   0   1   0   0   0   0   0   1   0   1   1   0   0   0   1   0   0   
3   0   0   0   1   0   1   0   0   0   0   0   0   1   0   0   1   0   1   1   

   19  
0   0  
1   1  
2   0  
3   1

In [23]:
pd.DataFrame(cvec_sent.toarray(),columns=cvec.get_feature_names_out())

best  black  brown  cat  chase  dog  friend  gate  green  ground  human  \
0     1      0      0    0      0    1       1     0      0       0      1   
1     0      1      1    1      1    1       0     1      1       0      0   
2     0      1      0    1      0    0       0     0      0       1      0   
3     0      0      0    1      0    1       0     0      0       0      0   

   in  is  jumps  of  over  playing  quick  react  to  
0   0   1      0   1     0        0      0      0   0  
1   0   0      1   0     1        0      0      0   1  
2   1   1      0   0     0        1      0      0   0  
3   0   1      0   0     1        0      1      1   1

## TFIDF Transformer

In [24]:
from sklearn.feature_extraction.text import TfidfTransformer

In [25]:
tfidf=TfidfTransformer()

In [26]:
tfidf

TfidfTransformer()

In [27]:
cvec_sent

<4x20 sparse matrix of type '<class 'numpy.int64'>'
	with 29 stored elements in Compressed Sparse Row format>

In [30]:
tfidf.fit(cvec_sent)

TfidfTransformer()

In [31]:
tfidf_sent=tfidf.transform(cvec_sent)

In [32]:
tfidf_sent

<4x20 sparse matrix of type '<class 'numpy.float64'>'
	with 29 stored elements in Compressed Sparse Row format>

In [33]:
tfidf_sent.toarray()

array([[0.45573244, 0.        , 0.        , 0.        , 0.        ,
        0.29088811, 0.45573244, 0.        , 0.        , 0.        ,
        0.45573244, 0.        , 0.29088811, 0.        , 0.45573244,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.28450092, 0.36085335, 0.23032802, 0.36085335,
        0.23032802, 0.        , 0.36085335, 0.36085335, 0.        ,
        0.        , 0.        , 0.        , 0.36085335, 0.        ,
        0.28450092, 0.        , 0.        , 0.        , 0.28450092],
       [0.        , 0.37431475, 0.        , 0.30304005, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.4747708 ,
        0.        , 0.4747708 , 0.30304005, 0.        , 0.        ,
        0.        , 0.4747708 , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.30205432, 0.        ,
        0.30205432, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.30205432, 0

## TFIDF-Vectorization(One step process)

In [34]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [35]:
tf_vec=TfidfVectorizer()

In [36]:
tf_vec

TfidfVectorizer()

In [37]:
sent

['Dog is best friend of human',
 'Brown Dog jumps over Green Gate to Chase Black Cat',
 'Black Cat is Playing in ground',
 'Cat is quick to react over dog']

In [38]:
tf_vec.fit(sent)

TfidfVectorizer()

In [39]:
tf_sent=tf_vec.transform(sent)

In [40]:
tf_sent

<4x20 sparse matrix of type '<class 'numpy.float64'>'
	with 29 stored elements in Compressed Sparse Row format>

In [41]:
tf_sent.toarray()

array([[0.45573244, 0.        , 0.        , 0.        , 0.        ,
        0.29088811, 0.45573244, 0.        , 0.        , 0.        ,
        0.45573244, 0.        , 0.29088811, 0.        , 0.45573244,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.28450092, 0.36085335, 0.23032802, 0.36085335,
        0.23032802, 0.        , 0.36085335, 0.36085335, 0.        ,
        0.        , 0.        , 0.        , 0.36085335, 0.        ,
        0.28450092, 0.        , 0.        , 0.        , 0.28450092],
       [0.        , 0.37431475, 0.        , 0.30304005, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.4747708 ,
        0.        , 0.4747708 , 0.30304005, 0.        , 0.        ,
        0.        , 0.4747708 , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.30205432, 0.        ,
        0.30205432, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.30205432, 0