In [2]:
import numpy as np 

# Various methods to create numpy array
## 1) Traditional method

In [2]:
a1=np.array([10,20,30,40,50])

In [3]:
a1

array([10, 20, 30, 40, 50])

In [4]:
type(a1)

numpy.ndarray

In [10]:
print(a1)

[10 20 30 40 50]


In [6]:
a1.ndim

1

In [7]:
a1.shape

(5,)

In [8]:
a1.size

5

In [9]:
a1.itemsize

4

In [11]:
a1.dtype

dtype('int32')

In [19]:
a2=np.array([[10,30,50,60,70],[56,78,89,54,43]])

In [20]:
a2

array([[10, 30, 50, 60, 70],
       [56, 78, 89, 54, 43]])

In [23]:
a2.itemsize

4

In [24]:
a2.shape

(2, 5)

In [25]:
a2.ndim

2

In [26]:
a2.dtype

dtype('int32')

## 2) Homogenous method

In [28]:
a1=np.ones((4,5))

In [29]:
a1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
np.ones((3,4),dtype=np.int64)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int64)

In [16]:
a1=np.ones((2,3,4),dtype='int32')

In [17]:
a1

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [18]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## 3) Diagonal method

In [19]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
np.eye(2,3)

array([[1., 0., 0.],
       [0., 1., 0.]])

In [22]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
np.identity(2,3)

TypeError: Cannot interpret '3' as a data type

## 4) Numerical method

In [3]:
np.arange(1,20,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [4]:
np.arange(5,20,0.5)

array([ 5. ,  5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ,
       10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5,
       16. , 16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5])

In [5]:
list(range(1,10,0.5)) # range does not take float values

TypeError: 'float' object cannot be interpreted as an integer

In [6]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [7]:
np.arange(-10,-30,-1)

array([-10, -11, -12, -13, -14, -15, -16, -17, -18, -19, -20, -21, -22,
       -23, -24, -25, -26, -27, -28, -29])

In [8]:
lin1=np.linspace(1,10,num=50)

In [9]:
lin1

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [10]:
lin1.shape

(50,)

In [11]:
lin1.ndim

1

In [14]:
lin2=np.linspace(1,2,num=20,retstep=True) # retstep gives the step value

In [16]:
lin2

(array([1.        , 1.05263158, 1.10526316, 1.15789474, 1.21052632,
        1.26315789, 1.31578947, 1.36842105, 1.42105263, 1.47368421,
        1.52631579, 1.57894737, 1.63157895, 1.68421053, 1.73684211,
        1.78947368, 1.84210526, 1.89473684, 1.94736842, 2.        ]),
 0.05263157894736842)

## 5) Random method

In [17]:
np.random.rand(3,4)

array([[0.05579601, 0.34946766, 0.61946679, 0.72622262],
       [0.55365058, 0.84029622, 0.36781322, 0.8123097 ],
       [0.13070815, 0.346324  , 0.23279112, 0.40749796]])

In [18]:
np.random.rand(2,3,4)

array([[[0.33533171, 0.18424274, 0.29427857, 0.62745594],
        [0.26709195, 0.53286313, 0.37626307, 0.07559362],
        [0.28038722, 0.42819183, 0.75706443, 0.93008949]],

       [[0.99348407, 0.16575162, 0.14367817, 0.66447066],
        [0.0522242 , 0.50903541, 0.44719219, 0.89899043],
        [0.58532447, 0.26186791, 0.60764033, 0.47942658]]])

In [19]:
np.random.randn(3,4)

array([[ 0.0071728 ,  2.12949343,  0.32081195, -0.44473521],
       [-1.11144903,  0.87727754, -1.09478612, -0.35057221],
       [ 0.04578982,  0.21490044, -0.59874096, -2.05950871]])

In [20]:
np.random.randint(10,20,(4,6))

array([[16, 17, 19, 17, 12, 16],
       [15, 14, 19, 15, 10, 13],
       [12, 18, 19, 18, 14, 13],
       [10, 11, 13, 12, 14, 15]])

In [21]:
np.random.randint(10,50,(2,3,4,5))

array([[[[34, 18, 28, 10, 27],
         [14, 38, 28, 26, 45],
         [31, 10, 15, 47, 27],
         [27, 27, 48, 35, 26]],

        [[31, 19, 20, 41, 37],
         [11, 42, 16, 40, 42],
         [48, 41, 43, 41, 45],
         [17, 28, 13, 20, 36]],

        [[15, 18, 23, 13, 34],
         [37, 38, 18, 26, 37],
         [42, 28, 42, 45, 43],
         [28, 19, 19, 26, 46]]],


       [[[30, 19, 31, 41, 47],
         [47, 19, 35, 36, 12],
         [17, 40, 39, 30, 28],
         [46, 30, 40, 47, 23]],

        [[45, 23, 49, 13, 44],
         [21, 35, 41, 45, 46],
         [40, 12, 45, 30, 36],
         [38, 24, 34, 46, 15]],

        [[21, 23, 27, 18, 41],
         [35, 10, 48, 32, 15],
         [22, 21, 13, 43, 10],
         [33, 12, 37, 24, 43]]]])

In [22]:
l1=[5,6,7,8]

In [23]:
l1

[5, 6, 7, 8]

In [25]:
np.random.choice(l1,size=(4,6),p=[0.20,0,0.30,0.50])

array([[8, 8, 8, 8, 7, 7],
       [5, 8, 7, 8, 7, 5],
       [7, 7, 5, 8, 8, 7],
       [7, 5, 8, 5, 5, 7]])

In [26]:
np.random.choice(l1,size=(4,6),p=[.5,.1,.2,.2])

array([[6, 5, 5, 6, 5, 5],
       [6, 5, 5, 5, 5, 5],
       [8, 6, 5, 7, 5, 8],
       [5, 5, 5, 5, 5, 8]])