## Indexing two dimension array

In [2]:
import numpy as np

In [3]:
a1=np.random.randint(100,200,(4,6))

In [4]:
a1

array([[110, 158, 166, 170, 130, 153],
       [124, 154, 126, 129, 158, 155],
       [197, 123, 141, 152, 173, 188],
       [160, 100, 110, 104, 109, 131]])

In [5]:
# To extract 152,109 and 100

In [6]:
a1[2,3]

152

In [7]:
a1[3,4]

109

In [8]:
a1[3,1]

100

## Indexing three dimension array

In [9]:
a2=np.random.randint(100,200,(2,3,4))

In [10]:
a2

array([[[172, 150, 166, 124],
        [199, 129, 114, 139],
        [161, 152, 117, 179]],

       [[106, 133, 104, 177],
        [193, 107, 132, 137],
        [183, 141, 126, 107]]])

In [11]:
# To extract 117 and 132

In [12]:
a2[0,2,2]

117

In [13]:
a2[1,1,2]

132

## Slicing two dimension array

In [14]:
a1

array([[110, 158, 166, 170, 130, 153],
       [124, 154, 126, 129, 158, 155],
       [197, 123, 141, 152, 173, 188],
       [160, 100, 110, 104, 109, 131]])

In [ ]:
'''To extract 126,129,158
              141,152,173'''

In [1]:
a1[1:3:1,2:5:1]

NameError: name 'a1' is not defined

## Slicing three dimension array

In [17]:
a2

array([[[172, 150, 166, 124],
        [199, 129, 114, 139],
        [161, 152, 117, 179]],

       [[106, 133, 104, 177],
        [193, 107, 132, 137],
        [183, 141, 126, 107]]])

In [21]:
''' To extract 129,114
               152,117
               107,132
               141,126'''

' To extract 129,114\n               152,117\n               107,132\n               141,126'

In [22]:
a2[:,1:3:1,1:3:1]

array([[[129, 114],
        [152, 117]],

       [[107, 132],
        [141, 126]]])

## Slicing four dimension array

In [23]:
a3=np.random.randint(100,200,(2,2,4,5))

In [24]:
a3

array([[[[170, 162, 167, 104, 114],
         [171, 185, 129, 157, 176],
         [174, 104, 139, 109, 173],
         [143, 133, 168, 145, 149]],

        [[126, 140, 129, 106, 134],
         [157, 189, 129, 113, 152],
         [165, 142, 197, 100, 168],
         [134, 195, 182, 194, 185]]],


       [[[194, 154, 120, 191, 179],
         [199, 108, 198, 116, 177],
         [130, 177, 149, 140, 121],
         [101, 111, 156, 148, 193]],

        [[100, 136, 122, 126, 188],
         [136, 146, 192, 137, 110],
         [133, 165, 129, 169, 135],
         [188, 180, 100, 105, 149]]]])

In [25]:
'''To extract 185,129,157
             104,139,109
             108,198,116
             177,149,140'''

'To extract 185,129,157\n             104,139,109\n             108,198,116\n             177,149,140'

In [26]:
a3[0:2:1,0:1:1,1:3:1,1:4:1]

array([[[[185, 129, 157],
         [104, 139, 109]]],


       [[[108, 198, 116],
         [177, 149, 140]]]])