## Numpy occupies less memory compared to that of list

In [1]:
import numpy as np
import sys

In [2]:
sys.getsizeof(5)

28

In [3]:
ary1=np.array([10,20])

In [4]:
ary1.size

2

In [5]:
ary1.itemsize # it will give the size of each element of ary1

4

In [6]:
list1=[100,200,300,400]

In [7]:
list1

[100, 200, 300, 400]

In [8]:
list1[0]

100

In [9]:
sys.getsizeof(list1[0])

28

In [10]:
var1=list(range(0,1000))

In [11]:
len(var1)

1000

In [12]:
sys.getsizeof(3)

28

In [13]:
sys.getsizeof(3)*len(var1)

28000

In [14]:
ary1=np.arange(0,1000)

In [15]:
ary1.size

1000

In [16]:
ary1.itemsize

4

In [17]:
ary1.itemsize*ary1.size

4000

## Numpy is very fast in execution

In [18]:
import time

In [19]:
l1=list(range(100000))

In [20]:
len(l1)

100000

In [21]:
l2=list(range(100000))

In [22]:
len(l2)

100000

In [23]:
l3=[]
st=time.time()
for i in range(100000):
    res=l1[i]+l2[i]
    l3.append(res)
et=time.time()
print('Time taken by list:',(et-st))

Time taken by list: 0.026273727416992188


In [24]:
np1=np.arange(100000)

In [25]:
len(np1)

100000

In [26]:
np2=np.arange(100000)

In [27]:
len(np2)

100000

In [28]:
st1=time.time()
npres=np1+np2
et1=time.time()
print('Time taken by numpy array:',(et1-st1))

Time taken by numpy array: 0.0009691715240478516


# Advanced indexing
## One dimension

In [29]:
a1=np.random.randint(10,50,(8))

In [30]:
a1

array([36, 18, 13, 11, 19, 47, 24, 32])

In [31]:
#37,36,41,26

In [32]:
ind=[1,3,4,7]

In [33]:
a1[ind]

array([18, 11, 19, 32])

In [34]:
a1[[1,3,4,7]]

array([18, 11, 19, 32])

## Two dimension

In [35]:
a2=np.random.randint(100,200,(4,6))

In [36]:
a2

array([[143, 100, 158, 101, 105, 175],
       [141, 120, 196, 189, 130, 155],
       [153, 110, 196, 104, 163, 180],
       [103, 192, 185, 101, 130, 148]])

In [37]:
# to extract 165,125,146,109,127

In [38]:
a2[[0,1,2,3,3],[1,2,4,0,2]]

array([100, 196, 163, 103, 185])

In [39]:
rind=[0,1,2,3,3]

In [40]:
cind=[1,2,4,0,2]

In [41]:
a2[rind,cind]

array([100, 196, 163, 103, 185])

## Three dimension

### 

In [42]:
a3=np.random.randint(20,100,(2,4,6))

In [43]:
a3

array([[[80, 70, 78, 93, 77, 69],
        [92, 83, 42, 68, 67, 24],
        [24, 85, 37, 91, 72, 84],
        [42, 97, 53, 89, 70, 35]],

       [[61, 88, 68, 31, 91, 74],
        [61, 57, 42, 49, 73, 32],
        [77, 60, 83, 67, 40, 24],
        [62, 99, 45, 27, 94, 32]]])

In [44]:
# to extract 82,39,43,73,26,49

In [45]:
a3[[0,1,0,1,0,1],[0,0,2,2,3,2],[0,2,2,1,4,5]]

array([80, 68, 37, 60, 70, 24])

# Boolean indexing

In [46]:
ary2=np.random.randint(10,200,(4,6))

In [47]:
ary2

array([[106,  20,  93,  83, 183, 199],
       [ 27,  96,  88, 116, 151, 156],
       [ 39,  88, 166, 158, 106,  22],
       [178, 116,  74,  59, 115, 165]])

In [48]:
ary2>100

array([[ True, False, False, False,  True,  True],
       [False, False, False,  True,  True,  True],
       [False, False,  True,  True,  True, False],
       [ True,  True, False, False,  True,  True]])

In [49]:
ary2[ary2>100]

array([106, 183, 199, 116, 151, 156, 166, 158, 106, 178, 116, 115, 165])

In [50]:
ary2>50 & ary2<150

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [51]:
ary2>50 and ary2<150

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [52]:
(ary2>50) and (ary2<1500)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [53]:
(ary2>50) & (ary2<1500)

array([[ True, False,  True,  True,  True,  True],
       [False,  True,  True,  True,  True,  True],
       [False,  True,  True,  True,  True, False],
       [ True,  True,  True,  True,  True,  True]])

In [54]:
ary2[(ary2>50) & (ary2<1500)]

array([106,  93,  83, 183, 199,  96,  88, 116, 151, 156,  88, 166, 158,
       106, 178, 116,  74,  59, 115, 165])

In [55]:
a1

array([36, 18, 13, 11, 19, 47, 24, 32])

In [56]:
import time
for i in a1:
    print(i)
    time.sleep(0.5)

36
18
13
11
19
47
24
32


In [57]:
a2

array([[143, 100, 158, 101, 105, 175],
       [141, 120, 196, 189, 130, 155],
       [153, 110, 196, 104, 163, 180],
       [103, 192, 185, 101, 130, 148]])

In [58]:
for x in a2:
    print(x)
    time.sleep(0.5)
    for y in x:
        print(y)
        time.sleep(0.5)

[143 100 158 101 105 175]
143
100
158
101
105
175
[141 120 196 189 130 155]
141
120
196
189
130
155
[153 110 196 104 163 180]
153
110
196
104
163
180
[103 192 185 101 130 148]
103
192
185
101
130
148


# Arithmetic operations

In [59]:
a1=np.arange(11,16)

In [60]:
a1

array([11, 12, 13, 14, 15])

In [61]:
a2=np.arange(1,6)

In [62]:
a2

array([1, 2, 3, 4, 5])

In [63]:
a1+a2

array([12, 14, 16, 18, 20])

In [64]:
a1-a2

array([10, 10, 10, 10, 10])

In [65]:
a1*a2

array([11, 24, 39, 56, 75])

In [66]:
a1/a2

array([11.        ,  6.        ,  4.33333333,  3.5       ,  3.        ])

In [67]:
np.add(a1,a2)

array([12, 14, 16, 18, 20])

In [68]:
a1+a2

array([12, 14, 16, 18, 20])

In [69]:
np.subtract(a1,a2)

array([10, 10, 10, 10, 10])

In [70]:
a1-a2

array([10, 10, 10, 10, 10])

In [71]:
np.multiply(a1,a2)

array([11, 24, 39, 56, 75])

In [72]:
a1*a2

array([11, 24, 39, 56, 75])

In [73]:
np.divide(a1,a2)

array([11.        ,  6.        ,  4.33333333,  3.5       ,  3.        ])

In [74]:
a1/a2

array([11.        ,  6.        ,  4.33333333,  3.5       ,  3.        ])

## operations on 2D array

In [75]:
np2=np.array([[1,2],[3,4]])

In [76]:
b2=np.array([[10,20],[10,10]])

In [77]:
display(np2,b2)

array([[1, 2],
       [3, 4]])

array([[10, 20],
       [10, 10]])

In [78]:
np2+b2

array([[11, 22],
       [13, 14]])

In [79]:
np2-b2

array([[ -9, -18],
       [ -7,  -6]])

In [80]:
a1

array([11, 12, 13, 14, 15])

In [81]:
a1+10

array([21, 22, 23, 24, 25])

In [82]:
a1*2

array([22, 24, 26, 28, 30])

## Different shapes

In [83]:
a1

array([11, 12, 13, 14, 15])

In [84]:
a2=np.arange(21,28)

In [85]:
a2

array([21, 22, 23, 24, 25, 26, 27])

In [86]:
a1+a2

ValueError: operands could not be broadcast together with shapes (5,) (7,) 

In [87]:
a1

array([11, 12, 13, 14, 15])

In [88]:
10

10

In [89]:
a1+10

array([21, 22, 23, 24, 25])

In [90]:
np2

array([[1, 2],
       [3, 4]])

In [91]:
b2

array([[10, 20],
       [10, 10]])

In [92]:
np2.shape

(2, 2)

In [93]:
b2.shape

(2, 2)

In [94]:
np2+b2

array([[11, 22],
       [13, 14]])

In [95]:
np2

array([[1, 2],
       [3, 4]])

In [96]:
c2=np.array([[10,20,30],[1,2,3]])

In [97]:
c2

array([[10, 20, 30],
       [ 1,  2,  3]])

In [98]:
np2.ndim

2

In [99]:
c2.ndim

2

In [100]:
np2.shape

(2, 2)

In [101]:
c2.shape

(2, 3)

In [102]:
np2+c2

ValueError: operands could not be broadcast together with shapes (2,2) (2,3) 

In [103]:
d2=np.array([[100,200]])

In [104]:
d2

array([[100, 200]])

In [105]:
d2.shape

(1, 2)

In [106]:
np2.ndim

2

In [107]:
d2.ndim

2

In [108]:
np2.shape

(2, 2)

In [109]:
np2+d2

array([[101, 202],
       [103, 204]])

In [110]:
a1

array([11, 12, 13, 14, 15])

In [111]:
5

5

In [112]:
a1+5

array([16, 17, 18, 19, 20])

In [113]:
n1=np.random.randint(10,50,(2,4,6))

In [114]:
n1

array([[[27, 39, 37, 31, 44, 42],
        [48, 38, 29, 23, 27, 12],
        [28, 30, 25, 16, 11, 41],
        [46, 30, 22, 31, 37, 41]],

       [[34, 46, 34, 25, 19, 44],
        [46, 38, 30, 13, 22, 25],
        [40, 11, 23, 49, 19, 49],
        [20, 29, 37, 32, 14, 19]]])

In [115]:
n1.ndim

3

In [116]:
n1.shape

(2, 4, 6)

In [117]:
n2=np.random.randint(10,30,(1,6))

In [118]:
display(n1.shape,n2.shape)

(2, 4, 6)

(1, 6)

In [119]:
n1+n2

array([[[49, 49, 47, 56, 66, 67],
        [70, 48, 39, 48, 49, 37],
        [50, 40, 35, 41, 33, 66],
        [68, 40, 32, 56, 59, 66]],

       [[56, 56, 44, 50, 41, 69],
        [68, 48, 40, 38, 44, 50],
        [62, 21, 33, 74, 41, 74],
        [42, 39, 47, 57, 36, 44]]])

In [120]:
n3=np.random.randint(10,40,(2,3,4))

In [121]:
n4=np.random.randint(10,30,(4,4))

In [122]:
display(n3.shape,n4.shape)

(2, 3, 4)

(4, 4)

In [123]:
n3+n4

ValueError: operands could not be broadcast together with shapes (2,3,4) (4,4) 