## Creating matrix

In [1]:
import numpy as np

In [2]:
ary1=np.array([100,200,300,400])

In [3]:
ary1

array([100, 200, 300, 400])

In [4]:
type(ary1)

numpy.ndarray

In [5]:
np.matrix([[100,200],[300,400]])

matrix([[100, 200],
        [300, 400]])

In [7]:
m1=np.matrix([[1,2],[3,4]])

In [8]:
m2=np.matrix([[2,2],[2,2]])

In [9]:
type(m1)

numpy.matrix

In [10]:
a1=np.array([[1,2],[3,4]])

In [11]:
a2=np.array([[2,2],[2,2]])

In [12]:
a1+a2

array([[3, 4],
       [5, 6]])

In [13]:
m1+m2

matrix([[3, 4],
        [5, 6]])

In [14]:
m1-m2

matrix([[-1,  0],
        [ 1,  2]])

In [15]:
display(a1,a2)

array([[1, 2],
       [3, 4]])

array([[2, 2],
       [2, 2]])

In [16]:
a1*a2 # elememt by element multiplication

array([[2, 4],
       [6, 8]])

In [17]:
m1*m2 # matrix multiplication

matrix([[ 6,  6],
        [14, 14]])

## Some other functions 

In [20]:
a1

array([[1, 2],
       [3, 4]])

In [21]:
np.linalg.det(a1)

-2.0000000000000004

In [25]:
ary2=np.array([100, 200,'NaN', 400])

In [26]:
ary2 # every element converted to string

array(['100', '200', 'NaN', '400'], dtype='<U11')

In [29]:
ary3=np.array([100, 200,np.nan, 400])

In [30]:
ary3

array([100., 200.,  nan, 400.])