# Manipulation
## 1)Transpose

In [1]:
import numpy as np

In [2]:
a1=np.random.randint(10,50,(4,5))

In [3]:
a1.ndim

2

In [4]:
a1.shape

(4, 5)

In [5]:
a1

array([[37, 31, 42, 10, 44],
       [41, 27, 19, 17, 38],
       [32, 27, 41, 16, 15],
       [20, 10, 46, 28, 36]])

In [6]:
a2=a1.transpose()

In [7]:
a1.T

array([[37, 41, 32, 20],
       [31, 27, 27, 10],
       [42, 19, 41, 46],
       [10, 17, 16, 28],
       [44, 38, 15, 36]])

In [8]:
a2

array([[37, 41, 32, 20],
       [31, 27, 27, 10],
       [42, 19, 41, 46],
       [10, 17, 16, 28],
       [44, 38, 15, 36]])

In [9]:
a2.shape

(5, 4)

In [10]:
a1.shape

(4, 5)

In [11]:
a3=np.random.randint(10,50,(2,4,6))

In [12]:
a3

array([[[32, 30, 20, 14, 16, 44],
        [10, 20, 40, 14, 36, 23],
        [23, 36, 34, 41, 16, 33],
        [11, 28, 15, 19, 31, 27]],

       [[21, 18, 35, 38, 17, 26],
        [42, 42, 33, 22, 10, 26],
        [14, 25, 36, 20, 11, 26],
        [37, 43, 12, 22, 45, 44]]])

In [13]:
a3.shape

(2, 4, 6)

In [14]:
a3.ndim

3

In [15]:
a3.transpose().shape

(6, 4, 2)

In [16]:
# 4,6,2

In [17]:
a3.transpose((1,2,0)).shape

(4, 6, 2)

In [18]:
a4=np.random.randint(10,50,(2,3,4,6))

In [19]:
a4

array([[[[20, 21, 30, 32, 42, 30],
         [30, 24, 16, 46, 38, 38],
         [46, 40, 14, 19, 12, 18],
         [18, 36, 17, 19, 48, 42]],

        [[43, 33, 41, 47, 13, 31],
         [31, 16, 23, 26, 48, 10],
         [28, 33, 36, 27, 15, 40],
         [40, 28, 18, 18, 42, 18]],

        [[46, 10, 33, 45, 17, 49],
         [16, 20, 39, 13, 31, 47],
         [20, 24, 15, 33, 22, 45],
         [46, 16, 24, 29, 39, 42]]],


       [[[38, 43, 23, 24, 49, 45],
         [15, 32, 44, 48, 24, 21],
         [37, 24, 14, 43, 16, 47],
         [10, 10, 36, 31, 29, 32]],

        [[37, 11, 48, 43, 17, 25],
         [20, 16, 10, 29, 39, 43],
         [20, 15, 38, 15, 16, 29],
         [42, 31, 27, 33, 24, 19]],

        [[39, 33, 14, 18, 49, 15],
         [18, 31, 46, 46, 34, 11],
         [49, 14, 10, 16, 46, 42],
         [46, 12, 20, 19, 28, 39]]]])

In [20]:
a4.shape

(2, 3, 4, 6)

In [21]:
a4.T.shape

(6, 4, 3, 2)

In [22]:
a4.transpose().shape

(6, 4, 3, 2)

In [23]:
#3,6,2,4

In [24]:
a4.transpose(1,3,0,2).shape

(3, 6, 2, 4)

## 2) Swapaxes

In [25]:
a2

array([[37, 41, 32, 20],
       [31, 27, 27, 10],
       [42, 19, 41, 46],
       [10, 17, 16, 28],
       [44, 38, 15, 36]])

In [26]:
a2.shape

(5, 4)

#### Swapaxes calling with array

In [27]:
a2.swapaxes(1,0)

array([[37, 31, 42, 10, 44],
       [41, 27, 19, 17, 38],
       [32, 27, 41, 16, 15],
       [20, 10, 46, 28, 36]])

In [28]:
a2.swapaxes(1,0).shape #OR

(4, 5)

In [29]:
a2.swapaxes(0,1).shape

(4, 5)

In [30]:
a3.shape

(2, 4, 6)

In [31]:
a3.swapaxes(2,0).shape # OR

(6, 4, 2)

In [32]:
a3.swapaxes(0,2).shape

(6, 4, 2)

In [33]:
a3.swapaxes(2,1).shape #OR

(2, 6, 4)

In [34]:
a3.swapaxes(1,2).shape

(2, 6, 4)

In [35]:
a4=np.random.randint(10,40,(2,3,4,5))

In [36]:
a4.shape

(2, 3, 4, 5)

In [37]:
a4.swapaxes(0,3).shape

(5, 3, 4, 2)

In [38]:
a4.swapaxes(2,1).shape

(2, 4, 3, 5)

#### Swapaxes calling with numpy

In [39]:
np.swapaxes(a4,1,3).shape

(2, 5, 4, 3)

## Reshape

In [40]:
ary1=np.arange(10,30)

In [41]:
ary1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [42]:
ary1.size

20

In [43]:
ary1.reshape(4,5)

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [44]:
ary1.reshape(5,4)

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25],
       [26, 27, 28, 29]])

In [45]:
ary1.reshape(5,5)

ValueError: cannot reshape array of size 20 into shape (5,5)

In [46]:
ary1.reshape(2,2,5)

array([[[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

## Resize

In [47]:
ary1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

#### Resize calling with array

In [48]:
ary1.resize(4,5)

In [49]:
ary1

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [50]:
ary1.resize(2,2,5) # Permanent change

In [51]:
ary1

array([[[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [52]:
ary1.resize(4,6)

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

In [53]:
ary1.reshape(4,6)

ValueError: cannot reshape array of size 20 into shape (4,6)

In [54]:
ary1.resize(4,6,refcheck=False)

In [55]:
ary1

array([[10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29,  0,  0,  0,  0]])

#### Resize calling with numpy

In [56]:
b1=np.arange(10,20)

In [57]:
b1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [58]:
b1.shape

(10,)

In [59]:
np.resize(b1,(2,5)) # not a permanent change

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [60]:
np.resize(b1,(3,6))

array([[10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [61]:
b1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [62]:
np.resize(b1,(6,4))

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [10, 11, 12, 13]])

## Flattening of array

### Flatten

In [63]:
c1=np.random.randint(10,50,(4,6))

In [64]:
c1

array([[43, 47, 23, 37, 32, 33],
       [22, 20, 43, 35, 20, 42],
       [17, 11, 42, 37, 43, 10],
       [12, 19, 34, 46, 39, 11]])

In [65]:
c1.ndim

2

In [66]:
c1.shape

(4, 6)

In [67]:
c1.size

24

In [68]:
c1_flat=c1.flatten() # by default 'order=C',C:contiguous(Row Major)
# flattened based on rows

In [69]:
c1_flat

array([43, 47, 23, 37, 32, 33, 22, 20, 43, 35, 20, 42, 17, 11, 42, 37, 43,
       10, 12, 19, 34, 46, 39, 11])

In [70]:
c1

array([[43, 47, 23, 37, 32, 33],
       [22, 20, 43, 35, 20, 42],
       [17, 11, 42, 37, 43, 10],
       [12, 19, 34, 46, 39, 11]])

In [71]:
c1_f=c1.flatten(order='F')

In [72]:
c1_f

array([43, 22, 17, 12, 47, 20, 11, 19, 23, 43, 42, 34, 37, 35, 37, 46, 32,
       20, 43, 39, 33, 42, 10, 11])

In [73]:
c2=np.random.randint(10,90,(2,4,6))

In [74]:
c2

array([[[15, 23, 44, 32, 67, 11],
        [60, 71, 72, 28, 81, 52],
        [50, 21, 14, 75, 59, 39],
        [22, 59, 50, 36, 22, 56]],

       [[75, 42, 75, 34, 72, 31],
        [55, 44, 76, 83, 63, 73],
        [15, 88, 34, 58, 31, 40],
        [83, 63, 28, 39, 62, 16]]])

In [75]:
c2_flat=c2.flatten()

In [76]:
c2_flat

array([15, 23, 44, 32, 67, 11, 60, 71, 72, 28, 81, 52, 50, 21, 14, 75, 59,
       39, 22, 59, 50, 36, 22, 56, 75, 42, 75, 34, 72, 31, 55, 44, 76, 83,
       63, 73, 15, 88, 34, 58, 31, 40, 83, 63, 28, 39, 62, 16])

In [77]:
c2

array([[[15, 23, 44, 32, 67, 11],
        [60, 71, 72, 28, 81, 52],
        [50, 21, 14, 75, 59, 39],
        [22, 59, 50, 36, 22, 56]],

       [[75, 42, 75, 34, 72, 31],
        [55, 44, 76, 83, 63, 73],
        [15, 88, 34, 58, 31, 40],
        [83, 63, 28, 39, 62, 16]]])

In [78]:
c2_f=c2.flatten(order='F')

In [79]:
c2_f

array([15, 75, 60, 55, 50, 15, 22, 83, 23, 42, 71, 44, 21, 88, 59, 63, 44,
       75, 72, 76, 14, 34, 50, 28, 32, 34, 28, 83, 75, 58, 36, 39, 67, 72,
       81, 63, 59, 31, 22, 62, 11, 31, 52, 73, 39, 40, 56, 16])

### Ravel

In [80]:
c1

array([[43, 47, 23, 37, 32, 33],
       [22, 20, 43, 35, 20, 42],
       [17, 11, 42, 37, 43, 10],
       [12, 19, 34, 46, 39, 11]])

In [81]:
np.ravel(c1)

array([43, 47, 23, 37, 32, 33, 22, 20, 43, 35, 20, 42, 17, 11, 42, 37, 43,
       10, 12, 19, 34, 46, 39, 11])

In [82]:
np.ravel(c1,order='F')

array([43, 22, 17, 12, 47, 20, 11, 19, 23, 43, 42, 34, 37, 35, 37, 46, 32,
       20, 43, 39, 33, 42, 10, 11])

In [83]:
c2

array([[[15, 23, 44, 32, 67, 11],
        [60, 71, 72, 28, 81, 52],
        [50, 21, 14, 75, 59, 39],
        [22, 59, 50, 36, 22, 56]],

       [[75, 42, 75, 34, 72, 31],
        [55, 44, 76, 83, 63, 73],
        [15, 88, 34, 58, 31, 40],
        [83, 63, 28, 39, 62, 16]]])

In [84]:
np.ravel(c2)

array([15, 23, 44, 32, 67, 11, 60, 71, 72, 28, 81, 52, 50, 21, 14, 75, 59,
       39, 22, 59, 50, 36, 22, 56, 75, 42, 75, 34, 72, 31, 55, 44, 76, 83,
       63, 73, 15, 88, 34, 58, 31, 40, 83, 63, 28, 39, 62, 16])

In [90]:
np.ravel(c2,order='F')

array([15, 75, 60, 55, 50, 15, 22, 83, 23, 42, 71, 44, 21, 88, 59, 63, 44,
       75, 72, 76, 14, 34, 50, 28, 32, 34, 28, 83, 75, 58, 36, 39, 67, 72,
       81, 63, 59, 31, 22, 62, 11, 31, 52, 73, 39, 40, 56, 16])

## Numpy Insert

In [93]:
d1=np.arange(11,50,7)

In [94]:
d1

array([11, 18, 25, 32, 39, 46])

In [95]:
np.insert(d1,2,99) # by default axis=None

array([11, 18, 99, 25, 32, 39, 46])

In [96]:
d1

array([11, 18, 25, 32, 39, 46])

In [100]:
np.insert(d1,3,[100,200],axis=None)

array([ 11,  18,  25, 100, 200,  32,  39,  46])

In [98]:
d1

array([11, 18, 25, 32, 39, 46])

In [99]:
np.insert(d1,[1,4],78)

array([11, 78, 18, 25, 32, 78, 39, 46])

In [102]:
d1

array([11, 18, 25, 32, 39, 46])

In [101]:
np.insert(d1,[1,4],[1000,2000])

array([  11, 1000,   18,   25,   32, 2000,   39,   46])

In [105]:
c1

array([[43, 47, 23, 37, 32, 33],
       [22, 20, 43, 35, 20, 42],
       [17, 11, 42, 37, 43, 10],
       [12, 19, 34, 46, 39, 11]])

In [125]:
np.insert(c1,1,999,axis=None) # it will flatten the array and find index 1 and then insert it

array([ 43, 999,  47,  23,  37,  32,  33,  22,  20,  43,  35,  20,  42,
        17,  11,  42,  37,  43,  10,  12,  19,  34,  46,  39,  11])

In [120]:
np.insert(c1,1,999,axis=0)

array([[ 43,  47,  23,  37,  32,  33],
       [999, 999, 999, 999, 999, 999],
       [ 22,  20,  43,  35,  20,  42],
       [ 17,  11,  42,  37,  43,  10],
       [ 12,  19,  34,  46,  39,  11]])

In [122]:
np.insert(c1,[2,3],999,axis=0)

array([[ 43,  47,  23,  37,  32,  33],
       [ 22,  20,  43,  35,  20,  42],
       [999, 999, 999, 999, 999, 999],
       [ 17,  11,  42,  37,  43,  10],
       [999, 999, 999, 999, 999, 999],
       [ 12,  19,  34,  46,  39,  11]])

In [114]:
c1

array([[43, 47, 23, 37, 32, 33],
       [22, 20, 43, 35, 20, 42],
       [17, 11, 42, 37, 43, 10],
       [12, 19, 34, 46, 39, 11]])

In [123]:
np.insert(c1,2,9,axis=1) 

array([[43, 47,  9, 23, 37, 32, 33],
       [22, 20,  9, 43, 35, 20, 42],
       [17, 11,  9, 42, 37, 43, 10],
       [12, 19,  9, 34, 46, 39, 11]])

In [124]:
np.insert(c1,[1,3],8,axis=1)

array([[43,  8, 47, 23,  8, 37, 32, 33],
       [22,  8, 20, 43,  8, 35, 20, 42],
       [17,  8, 11, 42,  8, 37, 43, 10],
       [12,  8, 19, 34,  8, 46, 39, 11]])

## Append

In [126]:
d1

array([11, 18, 25, 32, 39, 46])

In [127]:
np.append(d1,9999,axis=None) # by default axis=None

array([  11,   18,   25,   32,   39,   46, 9999])

In [128]:
c1

array([[43, 47, 23, 37, 32, 33],
       [22, 20, 43, 35, 20, 42],
       [17, 11, 42, 37, 43, 10],
       [12, 19, 34, 46, 39, 11]])

In [129]:
np.append(c1,9999,axis=None) # it will flatten the array first

array([  43,   47,   23,   37,   32,   33,   22,   20,   43,   35,   20,
         42,   17,   11,   42,   37,   43,   10,   12,   19,   34,   46,
         39,   11, 9999])

In [130]:
c1

array([[43, 47, 23, 37, 32, 33],
       [22, 20, 43, 35, 20, 42],
       [17, 11, 42, 37, 43, 10],
       [12, 19, 34, 46, 39, 11]])

In [137]:
np.append(c1,11,axis=0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 0 dimension(s)

In [133]:
np.append(c1,[[11,11,11,11,11,11]],axis=0) # check the square brackets and compare with the insert function syntax

array([[43, 47, 23, 37, 32, 33],
       [22, 20, 43, 35, 20, 42],
       [17, 11, 42, 37, 43, 10],
       [12, 19, 34, 46, 39, 11],
       [11, 11, 11, 11, 11, 11]])

In [136]:
np.append(c1,[[11],[11],[11],[11]],axis=1) # check the square brackets

array([[43, 47, 23, 37, 32, 33, 11],
       [22, 20, 43, 35, 20, 42, 11],
       [17, 11, 42, 37, 43, 10, 11],
       [12, 19, 34, 46, 39, 11, 11]])

## Delete

In [138]:
d1

array([11, 18, 25, 32, 39, 46])

In [140]:
np.delete(d1,2,axis=None)

array([11, 18, 32, 39, 46])

In [141]:
c1

array([[43, 47, 23, 37, 32, 33],
       [22, 20, 43, 35, 20, 42],
       [17, 11, 42, 37, 43, 10],
       [12, 19, 34, 46, 39, 11]])

In [143]:
np.delete(c1,2,axis=None) # it will flatten first and then delete

array([43, 47, 37, 32, 33, 22, 20, 43, 35, 20, 42, 17, 11, 42, 37, 43, 10,
       12, 19, 34, 46, 39, 11])

In [146]:
np.delete(c1,2,axis=0)

array([[43, 47, 23, 37, 32, 33],
       [22, 20, 43, 35, 20, 42],
       [12, 19, 34, 46, 39, 11]])

In [150]:
c1

array([[43, 47, 23, 37, 32, 33],
       [22, 20, 43, 35, 20, 42],
       [17, 11, 42, 37, 43, 10],
       [12, 19, 34, 46, 39, 11]])

In [147]:
np.delete(c1,1,axis=0)

array([[43, 47, 23, 37, 32, 33],
       [17, 11, 42, 37, 43, 10],
       [12, 19, 34, 46, 39, 11]])

In [148]:
c1

array([[43, 47, 23, 37, 32, 33],
       [22, 20, 43, 35, 20, 42],
       [17, 11, 42, 37, 43, 10],
       [12, 19, 34, 46, 39, 11]])

In [149]:
np.delete(c1,2,axis=1)

array([[43, 47, 37, 32, 33],
       [22, 20, 35, 20, 42],
       [17, 11, 37, 43, 10],
       [12, 19, 46, 39, 11]])

## Concatenate

In [151]:
d1

array([11, 18, 25, 32, 39, 46])

In [152]:
d2=np.arange(20,26)

In [153]:
d2

array([20, 21, 22, 23, 24, 25])

In [154]:
d1+d2

array([31, 39, 47, 55, 63, 71])

In [156]:
np.concatenate((d1,d2)) # double parenthesis

array([11, 18, 25, 32, 39, 46, 20, 21, 22, 23, 24, 25])

In [157]:
d1.shape

(6,)

In [158]:
d2.shape

(6,)

In [159]:
d3=np.arange(10,19)

In [160]:
d3

array([10, 11, 12, 13, 14, 15, 16, 17, 18])

In [161]:
d3.shape

(9,)

In [163]:
np.concatenate((d1,d3))

array([11, 18, 25, 32, 39, 46, 10, 11, 12, 13, 14, 15, 16, 17, 18])

In [164]:
n1=np.arange(1,5).reshape(2,2)

In [165]:
n1

array([[1, 2],
       [3, 4]])

In [166]:
n2=np.arange(11,15).reshape(2,2)

In [167]:
n2

array([[11, 12],
       [13, 14]])

In [168]:
np.concatenate((n1,n2)) # one above the other for axis=0(default). There is no any concept of axis=None so don't be confused

array([[ 1,  2],
       [ 3,  4],
       [11, 12],
       [13, 14]])

In [169]:
np.concatenate((n1,n2),axis=1) # side by side for axis=1.

array([[ 1,  2, 11, 12],
       [ 3,  4, 13, 14]])

In [170]:
n3=np.random.randint(1,5,(2,3))

In [171]:
n3

array([[3, 1, 2],
       [3, 1, 3]])

In [172]:
n3.shape

(2, 3)

In [173]:
n2.shape

(2, 2)

In [175]:
np.concatenate((n2,n3),axis=0)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3

In [176]:
np.concatenate((n2,n3),axis=1) # possible here

array([[11, 12,  3,  1,  2],
       [13, 14,  3,  1,  3]])